### PR TITLE
Discover plugins first and load them after.

### LINKED ISSUE #63: Loading other plugins fails when a plugin interacts with filesystem in red4ext/plugins/
RED4ext: v1.24.3

I'm currently implementing a migration routine, moving from `<game>/red4ext/plugins/RedFileSystem/storages` to `<game>/r6/storages`. I recursively copy files to the new directory, and delete the old directory, without errors. However, next plugins to be loaded by RED4ext are ignored (no log about them + crash because ofc native definitions are not found by redscript). If I run again, routine is not triggered, and all plugins are loaded as expected. Migration routine is called within `RED4ext::EMainReason::Load` callback, after registering types.

Culprit should be when [iterating](https://github.com/WopsS/RED4ext/blob/6f64d6ae515bb99ddfc8ff085db493ab3f19af46/src/dll/Systems/PluginSystem.cpp#L65) over plugins and [loading](https://github.com/WopsS/RED4ext/blob/6f64d6ae515bb99ddfc8ff085db493ab3f19af46/src/dll/Systems/PluginSystem.cpp#L129) them at the same time.

I'll look into this and propose a PR to first discover/queue plugins and load them after.

Workaround: only copy directory, and remove it when `Unload` is triggered.

### PR DESCRIPTION
**Pull request by poirierlouis**
Loading a plugin while iterating through path of plugins can invalidate `recursive_directory_iterator`. It happens when a plugin change its directory's structure (remove operation). It stops and ignores loading of remaining plugins.

This will queue path of detected plugins, and only load them after.

Closes #63

### CODE REVIEW

File: src/dll/Systems/PluginSystem.hpp [hunk 1]
```diff
@@ -25,6 +25,12 @@ class PluginSystem : public ISystem
     using Map_t = std::unordered_map<HMODULE, std::shared_ptr<PluginBase>>;
     using MapIter_t = Map_t::iterator;
 
+    struct PluginEntry
```
Comment (WopsS) [inline src/dll/Systems/PluginSystem.hpp:28]: I think this name can be a bit confusing if you do not look at the context of where it is used. I would suggest `PluginLoadInfo`, what do you think?

**Review by WopsS — CHANGES_REQUESTED** [review]
Thanks!

I have a remark regarding the struct name 🏃

File: src/dll/Systems/PluginSystem.hpp (hunk 1 above)
Comment (poirierlouis) [reply src/dll/Systems/PluginSystem.hpp:28]: I was not convinced myself, I'll update it soon.

**Review by WopsS — APPROVED** [review]
Thanks!
